import { useState } from 'react'

const SECTIONS = [
  {
    id: 'overview', icon: 'ti-home', title: 'Portal Overview', color: '#007B8A',
    content: `The salescode.ai Load & Stress Testing Portal is a self-hosted tool for testing API performance across multiple Lines of Business (LOBs). It generates k6 and JMeter scripts automatically, runs tests, and produces professional PDF reports.`,
    points: [
      'Supports multiple LOBs — each with their own credentials, base URL and token',
      'Auto-generates test scripts — no manual scripting needed',
      'Progressive load testing — scale VUs from 30 → 200 across multiple iterations',
      'PDF reports with charts, metrics, and recommendations',
    ],
  },
  {
    id: 'lobs', icon: 'ti-building', title: 'Lines of Business (LOBs)', color: '#1565C0',
    content: `Each LOB represents a client environment (e.g. cokesademo, hccbckinddemo). LOBs have their own base URL, credentials, and token. The token is auto-generated by calling the /signin endpoint with encrypted credentials.`,
    points: [
      'Select environment: UAT / Demo / Prod — base URL auto-fills',
      'LOB list loaded dynamically from /hckeck API — always up to date',
      'Credentials stored securely — token auto-refreshed on demand',
      'Token status visible in the list — green = ready, amber = needs refresh',
    ],
    tips: ['Always refresh the token before running a long test', 'Use "Check connectivity" to verify the environment is reachable'],
  },
  {
    id: 'apis', icon: 'ti-api', title: 'API Library', color: '#6A1B9A',
    content: `The API library is a master catalog of all available endpoints. Each API stores its method, endpoint path, description, and default request body. APIs can have a base URL override for endpoints on different domains.`,
    points: [
      'GET APIs — read-only, safe to run against production',
      'POST/PUT/DELETE — write APIs, use with caution on prod',
      'Base URL override — for APIs on different domains (e.g. rewardsdemo.sellina.io)',
      'Default body — used if no LOB-specific body is set',
    ],
    tips: ['Use the Beautify JSON button to format request bodies', 'Name APIs clearly — the name appears in test reports'],
  },
  {
    id: 'mapping', icon: 'ti-arrows-exchange', title: 'LOB ↔ API Mapping', color: '#E65100',
    content: `Mapping connects LOBs to their APIs. Each LOB can use a different subset of APIs with different traffic weights and custom request bodies. The total weight should always sum to 100%.`,
    points: [
      'Enable/disable APIs per LOB using checkboxes',
      'Weight % controls traffic distribution — 50/50 means equal split',
      'Custom body per LOB — override default with LOB-specific data (outletCode, loginId etc.)',
      'Save shows a confirmation to validate bodies before saving',
    ],
    tips: ['Validate your request body with real data before running tests', 'Higher weight = more requests to that API during the test'],
  },
  {
    id: 'testconfig', icon: 'ti-player-play', title: 'Test Configuration', color: '#2E7D32',
    content: `Test Config is where you run load tests. Two modes: Single run (fixed VUs) and Progressive iterations (scale VUs from low to high, matching your sample report format).`,
    points: [
      'Single run — quick smoke test or regular load test',
      'Progressive iterations — 30 → 60 → 120 → 200 VUs, generates combined report',
      'API filter — run All, GET only (safe), or POST only',
      'Prod warning — automatic alert when selecting a production LOB',
    ],
    tips: ['Use Smoke preset (5 VUs, 60s) first to confirm APIs are working', 'For production testing, always use GET only filter'],
  },
  {
    id: 'reports', icon: 'ti-chart-bar', title: 'Reports & PDF', color: '#C62828',
    content: `Reports show detailed metrics for every completed test run. The PDF report includes a bar chart, metric definitions, per-endpoint breakdown, and recommendations — ready to share with stakeholders.`,
    points: [
      'p50/p90/p99 — response time percentiles (see definitions below)',
      'Error rate — % of failed requests, target is always 0%',
      'Throughput (RPS) — requests per second processed',
      'PASS/FAIL verdict based on configurable thresholds per LOB',
    ],
    tips: ['Edit the observation text before downloading — personalise for your audience', 'Set realistic thresholds per LOB — prod may need stricter limits than demo'],
  },
  {
    id: 'metrics', icon: 'ti-info-circle', title: 'Metric Definitions', color: '#007B8A',
    content: `Understanding percentile metrics is key to interpreting load test results correctly.`,
    defs: [
      { term: 'p50 (Median)', def: 'Half of all requests responded faster than this. Best represents the "typical" user experience.' },
      { term: 'p90', def: '90% of requests responded faster than this. Shows what most users experience. If high, many users are seeing slow pages.' },
      { term: 'p99', def: '99% of requests responded faster than this. Your worst-case performance. If p99=2s, 1 in 100 users waits 2 seconds.' },
      { term: 'Error Rate', def: 'Percentage of requests that returned 4xx or 5xx errors. Should always be 0% in a passing test.' },
      { term: 'Throughput (RPS)', def: 'Requests per second processed by the server. Higher is better — shows system capacity.' },
      { term: 'Virtual Users (VUs)', def: 'Simulated concurrent users all hitting the API simultaneously. 50 VUs = 50 users at the same time.' },
      { term: 'Ramp-up', def: 'Time taken to gradually increase from 0 to max VUs. Prevents a sudden spike that could cause false failures.' },
    ],
  },
]

export default function Docs() {
  const [active, setActive] = useState('overview')
  const section = SECTIONS.find(s => s.id === active)

  return (
    <div className="flex min-h-screen" style={{fontFamily:'Arial,Helvetica,sans-serif'}}>
      {/* Doc sidebar */}
      <div className="w-52 border-r border-gray-100 bg-white py-6 px-3 flex-shrink-0">
        <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide px-3 mb-3">Contents</p>
        {SECTIONS.map(s => (
          <button key={s.id} onClick={() => setActive(s.id)}
            className={`w-full text-left flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm mb-0.5 transition-colors ${
              active === s.id ? 'text-white font-medium' : 'text-gray-600 hover:bg-gray-50'
            }`}
            style={active === s.id ? {background: s.color} : {}}>
            <i className={`ti ${s.icon} text-sm`} style={{color: active === s.id ? 'white' : s.color}} />
            {s.title}
          </button>
        ))}
      </div>

      {/* Doc content */}
      <div className="flex-1 p-8 max-w-3xl">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{background: section.color + '15'}}>
            <i className={`ti ${section.icon} text-xl`} style={{color: section.color}} />
          </div>
          <div>
            <h1 className="text-xl font-semibold text-gray-900">{section.title}</h1>
            <p className="text-xs text-gray-400 mt-0.5">salescode.ai Load & Stress Testing Portal</p>
          </div>
        </div>

        {/* Description */}
        <div className="bg-gray-50 rounded-xl p-4 mb-5 text-sm text-gray-700 leading-relaxed border border-gray-100">
          {section.content}
        </div>

        {/* Key points */}
        {section.points && (
          <div className="mb-5">
            <h3 className="text-sm font-semibold text-gray-900 mb-3">Key points</h3>
            <div className="space-y-2">
              {section.points.map((p, i) => (
                <div key={i} className="flex items-start gap-2.5 text-sm text-gray-700">
                  <span className="w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 text-xs font-bold text-white" style={{background: section.color}}>{i+1}</span>
                  {p}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Definitions */}
        {section.defs && (
          <div className="mb-5">
            <h3 className="text-sm font-semibold text-gray-900 mb-3">Definitions</h3>
            <div className="space-y-2">
              {section.defs.map((d, i) => (
                <div key={i} className="rounded-xl p-3 border text-sm" style={{borderColor: section.color + '30', background: section.color + '08'}}>
                  <span className="font-semibold" style={{color: section.color}}>{d.term}</span>
                  <span className="text-gray-600 ml-2">— {d.def}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Tips */}
        {section.tips && (
          <div className="rounded-xl p-4 border-l-4" style={{borderColor: section.color, background: section.color + '08'}}>
            <div className="flex items-center gap-2 mb-2">
              <i className="ti ti-bulb text-sm" style={{color: section.color}} />
              <span className="text-sm font-semibold" style={{color: section.color}}>Tips & best practices</span>
            </div>
            {section.tips.map((t, i) => (
              <p key={i} className="text-sm text-gray-600 mb-1">• {t}</p>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
