import json
import base64
import xml.etree.ElementTree as ET
from xml.dom import minidom
import urllib.parse


def _build_auth(lob):
    """Returns (header_name, header_value, query_suffix)"""
    t   = lob.auth_type
    name = lob.auth_header_name or 'authorization'
    val  = lob.auth_header_value or ''

    if t == 'bearer':
        return name, f'Bearer {val}', ''
    elif t == 'basic':
        encoded = base64.b64encode(val.encode()).decode()
        return name, f'Basic {encoded}', ''
    elif t == 'api_key_header':
        return name, val, ''
    elif t == 'api_key_query':
        param = name
        return None, None, f'?{param}={val}'
    else:  # custom
        return name, val, ''


def generate_jmx(lob, mappings, virtual_users, duration_seconds, ramp_up_seconds, iterations=None):
    enabled = [m for m in mappings if m.enabled]
    if not enabled:
        raise ValueError("No APIs enabled for this LOB")

    header_name, header_value, query_suffix = _build_auth(lob)

    parsed = urllib.parse.urlparse(lob.base_url)
    host = parsed.hostname or lob.base_url
    port = str(parsed.port or (443 if parsed.scheme == "https" else 80))
    protocol = parsed.scheme or "https"

    jmx = f"""<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.5">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="{lob.name} Load Test" enabled="true">
      <stringProp name="TestPlan.comments">Auto-generated by LoadTest Portal</stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments">
        <collectionProp name="Arguments.arguments">
          <elementProp name="BASE_URL" elementType="Argument">
            <stringProp name="Argument.name">BASE_URL</stringProp>
            <stringProp name="Argument.value">{lob.base_url}</stringProp>
          </elementProp>
          <elementProp name="TOKEN" elementType="Argument">
            <stringProp name="Argument.name">TOKEN</stringProp>
            <stringProp name="Argument.value">{lob.auth_header_value}</stringProp>
          </elementProp>
        </collectionProp>
      </elementProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="{lob.name} Users" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController">
          <boolProp name="LoopController.continue_forever">{str(iterations is None).lower()}</boolProp>
          <stringProp name="LoopController.loops">{iterations if iterations else -1}</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">{virtual_users}</stringProp>
        <stringProp name="ThreadGroup.ramp_time">{ramp_up_seconds}</stringProp>
        <boolProp name="ThreadGroup.scheduler">{str(iterations is None).lower()}</boolProp>
        <stringProp name="ThreadGroup.duration">{duration_seconds}</stringProp>
        <stringProp name="ThreadGroup.delay">0</stringProp>
      </ThreadGroup>
      <hashTree>
        <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="Auth Headers" enabled="true">
          <collectionProp name="HeaderManager.headers">"""

    if header_name:
        jmx += f"""
            <elementProp name="{header_name}" elementType="Header">
              <stringProp name="Header.name">{header_name}</stringProp>
              <stringProp name="Header.value">{header_value}</stringProp>
            </elementProp>"""

    jmx += """
            <elementProp name="Content-Type" elementType="Header">
              <stringProp name="Header.name">Content-Type</stringProp>
              <stringProp name="Header.value">application/json</stringProp>
            </elementProp>
          </collectionProp>
        </HeaderManager>
        <hashTree/>"""

    for m in enabled:
        body = ""
        if m.api_method in ("POST", "PUT", "PATCH"):
            raw = m.custom_body or m.api.default_body or "{}"
            try:
                body = json.dumps(json.loads(raw))
            except Exception:
                body = raw

        endpoint = m.api.endpoint + query_suffix
        # Escape XML special characters in endpoint
        endpoint_xml = endpoint.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')
        method = m.api_method
        name = m.api.name

        # use API-level base URL override if present
        api_base_url = m.api.base_url_override or lob.base_url
        api_parsed = urllib.parse.urlparse(api_base_url)
        ep_host = api_parsed.hostname or host
        ep_port = str(api_parsed.port or (443 if api_parsed.scheme == 'https' else 80))
        ep_protocol = api_parsed.scheme or protocol

        body_block = ""
        if body:
            body_block = f"""
          <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments">
            <collectionProp name="Arguments.arguments">
              <elementProp name="" elementType="HTTPArgument">
                <boolProp name="HTTPArgument.always_encode">false</boolProp>
                <stringProp name="Argument.value">{body}</stringProp>
                <stringProp name="Argument.metadata">=</stringProp>
              </elementProp>
            </collectionProp>
          </elementProp>"""
        else:
            body_block = """
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>"""

        jmx += f"""
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="{name}" enabled="true">
          <stringProp name="HTTPSampler.domain">{ep_host}</stringProp>
          <stringProp name="HTTPSampler.port">{ep_port}</stringProp>
          <stringProp name="HTTPSampler.protocol">{ep_protocol}</stringProp>
          <stringProp name="HTTPSampler.path">{endpoint_xml}</stringProp>
          <stringProp name="HTTPSampler.method">{method}</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>{body_block}
        </HTTPSamplerProxy>
        <hashTree>
          <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Assert 2xx" enabled="true">
            <collectionProp name="Asserion.test_strings">
              <stringProp name="49586">2[0-9][0-9]</stringProp>
            </collectionProp>
            <stringProp name="Assertion.custom_message"/>
            <stringProp name="Assertion.test_field">Assertion.response_code</stringProp>
            <boolProp name="Assertion.assume_success">false</boolProp>
            <intProp name="Assertion.test_type">1</intProp>
          </ResponseAssertion>
          <hashTree/>
        </hashTree>"""

    jmx += """
        <ResultCollector guiclass="SummaryReport" testclass="ResultCollector" testname="Summary Report" enabled="true">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <objProp><name>saveConfig</name>
            <value class="SampleSaveConfiguration">
              <time>true</time><latency>true</latency><timestamp>true</timestamp>
              <success>true</success><label>true</label><code>true</code>
              <message>true</message><threadName>true</threadName>
              <dataType>true</dataType><encoding>false</encoding>
              <assertions>true</assertions><subresults>true</subresults>
              <responseData>false</responseData><samplerData>false</samplerData>
              <xml>false</xml><fieldNames>true</fieldNames>
              <responseHeaders>false</responseHeaders><requestHeaders>false</requestHeaders>
              <responseDataOnError>false</responseDataOnError><saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
              <bytes>true</bytes><sentBytes>true</sentBytes><url>true</url>
              <threadCounts>true</threadCounts><idleTime>true</idleTime><connectTime>true</connectTime>
            </value>
          </objProp>
          <stringProp name="filename"/>
        </ResultCollector>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>"""

    return jmx
